# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
#- task: AzurePowerShell@5
#  inputs:
#    azureSubscription: 'ITOPS-Test (d1cdb2f3-d4f5-4429-8e39-d6a919b93ffb)'
#    ScriptType: 'InlineScript'
#    Inline: |
#      Get-Modules az -ListAvailable
#      bicep --version
#      $env:PSModulePath.ToString().Split(";") | Get-ChildItem | Where-Object -Property Name -Like "az.*" | Group-Object | Select-Object Name, count
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ITOPS-Test (d1cdb2f3-d4f5-4429-8e39-d6a919b93ffb)'
    subscriptionId: 'd1cdb2f3-d4f5-4429-8e39-d6a919b93ffb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'peterrg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/haelvoetpeter/peter/blob/master/CreateDb/sqlserver.json'
    overrideParameters: '-projectName peter99'
    deploymentMode: 'Incremental'
    deploymentName: 'DeploySQLTemplate'